# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      # - id: check-yaml
      - id: check-added-large-files
        exclude: "poetry.lock"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0" # replace with latest tag on GitHub
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3" # add version here
    hooks:
      - id: poetry-check
        args: ["-C", "./service/"]
      - id: poetry-lock
        args: ["-C", "./service/"]
      - id: poetry-export
        args: ["-C", "./service/"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd ./service && exec ./.venv/bin/pytest ./tests'
        language: system
        types: [python]
        pass_filenames: false
