services:
  api:
    # build:
    #   context: ./service
    image: ghcr.io/fleer/cistern_monitor-service:main
    # restart: unless-stopped
    container_name: api
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STAGE=prod
      - CISTERN_HEIGHT=250.5
      - MAX_LITER=5000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
