services:
  backend:
    build:
      context: ./service
    # image: ghcr.io/fleer/cistern_monitor-service:main
    # restart: unless-stopped
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STAGE=prod
      - CISTERN_HEIGHT=250.5
      - CISTERN_MAX_LITER=5000
      - CISTERN_SENSOR_DISTANCE=20.0
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextapp:
    container_name: nextapp
    image: nextapp
    environment:
      - SERVICE_URL=http://backend:8000
    build:
      context: ./cistern_dashboard
    ports:
      - 3000:3000
    depends_on:
      - backend
volumes:
  pgdata:
