"""Added cistern table.

Revision ID: caf112a8008d
Revises:
Create Date: 2024-07-13 00:14:39.928308

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caf112a8008d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cistern",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "measurement",
            sa.Integer(),
            nullable=False,
            comment="Raw Sensor Measurement",
        ),
        sa.Column(
            "liters", sa.Integer(), nullable=False, comment="Calculate Liters of Water"
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation Date",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_cistern_id"), "cistern", ["id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    op.drop_index(op.f("ix_public_cistern_id"), table_name="cistern", schema="public")
    op.drop_table("cistern", schema="public")
    # ### end Alembic commands ###
