name: Test Service

on:
  pull_request:
    paths:
      - service/**
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: ./.github/workflows/python_test.yaml
    with:
      work-dir: service/
