name: Linting and Testing - Node

on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
        working-directory: ${{ inputs.work-dir }}
      - name: Lint
        run: |
          npm run lint
          # npm run build --if-present
          # npm test
        working-directory: ${{ inputs.work-dir }}
